version: 2.1
orbs:
  heroku: circleci/heroku@2.0
jobs:
  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a jonathan-su-devops
            heroku container:push web -a jonathan-su-devops
            heroku container:release web -a jonathan-su-devops

workflows:
  simple_workflow:
    jobs:
      - deploy
